#Clean

#====== [Load Clean] =====

#Data was cleaned in excel to match coordinate data (distance from high tide)
  #and results of each quadrat

#import data. NAs were entered as "-" so include transforming them into NA
inv.d <- read.csv(file.choose("invertebrate"), stringsAsFactors = FALSE, 
                  strip.white = TRUE, na.strings = c("NA","-"))

tail(inv.d) #successfully transformed dashes to NA

#We can see that data has only been entered for quadrats in which there were 
  #species, however if we want to represent all the data gathered we need to 
  #include the result of 0 for those quadrats w/ no species found 

#import coordinate data for every quadrat
coor.d <- read.csv(file.choose("coordinate"), stringsAsFactors = FALSE, 
                   strip.white = TRUE, na.strings = c("NA","-"))

head(coor.d)

#I want to start by making a new column of the pasted section and quadrat values
inv.d[,16] <- paste(inv.d$Section, inv.d$Quadrat, sep = "")
head(inv.d) #looks good!

nrow(inv.d) #118

#create object for target values to be stored, it is the length of the amount of
  #quadrats in that section

#in this case the vector is a quotation of the site (ex: "E")
f.noquad <- function(sitelab) {

  #we start by defining how many quadrats were in each site
  quadnum <- length(grep(sitelab, coor.d$Section))
  print(quadnum)
  
  #create an object to store target values the length of # of quads
  targ <- rep("NA", quadnum)

  for(i in 1:quadnum) {
    #create target value to search for
    targ[i] <- c(paste(sitelab, i, sep = ""))
  }
  #because i want the next for loop to only compare to one object (the final 
    #sequence generated by the above) I seperated the loops
  
    for(i in 1:quadnum) {
      #This if asks the the sequence of quads exists and if it doesn't (number 
        #of positions containing that value == 0) than it will create an empty 
        #row
      newrow <- nrow(inv.d)
      
      if(length(grep(targ[i], inv.d$X)) == 0) 
        test[i] <- c(TRUE)
        #inv.d[i,] <- rbind(rep(NA, ncol(inv.d)))
    }
  print(test)

}

test <- rep("NA", 9)
f.noquad("H")

tail(inv.d)


inv.d[118 + i,] <- rbind(rep(NA, ncol(inv.d)))
tail(inv.d)
